apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-alertmanager-config
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: alertmanager
data:
  # To learn more: https://prometheus.io/docs/alerting/configuration/
  alertmanager.yml: |
    global: null
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
